spring:
  application:
    name: biometric-storage-api

  #  Configurations for the database
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/biodb}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}

  #  Configurations for the JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/biodb}
          username: ${POSTGRES_USER:root}
          password: ${POSTGRES_PASSWORD:root}
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurations for the server
server:
  port: 8765

#  Configurations for the JWT
security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}

