spring:
  application:
    name: biometric-storage-api

  #  Configurations for the database
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/biodb}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}

  #  Configurations for the JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection:
          url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/biodb}
          username: ${POSTGRES_USER:root}
          password: ${POSTGRES_PASSWORD:root}
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurations for the server
server:
  port: 8765

#  Configurations for the JWT
security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION_TIME:8640000}


minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:OtwRLldr3MVNdgPnNTRq}
  secret-key: ${MINIO_SECRET_KEY:SDVwPNDnPPfPnZLvBXkF8Uw0Xa8QicgwZUXMzGZ7}
  backet-name: ${MINIO_BACKET_NAME:name}
#  expiration-time: 2 days in milliseconds
  expirationTime: ${MINIO_EXPIRATION_TIME:600000}

#spring:
#  application:
#    name: biometric-storage-api
#
#  #  Configurations for the database
#  datasource:
#    url: ${DATASOURCE_URL}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}
#
#  #  Configurations for the JPA
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        connection:
#          url: ${DATASOURCE_URL}
#          username: ${POSTGRES_USER}
#          password: ${POSTGRES_PASSWORD}
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
## Configurations for the server
#server:
#  port: 8765
#
##  Configurations for the JWT
#security:
#  jwt:
#    secret-key: ${JWT_SECRET}
#    expiration-time: ${JWT_EXPIRATION_TIME}
#
#
#minio:
#  url: ${MINIO_URL}
#  access-key: ${MINIO_ACCESS_KEY}
#  secret-key: ${MINIO_SECRET_KEY}
#  backet-name: ${MINIO_BACKET_NAME}
#  #  expiration-time: 2 days in milliseconds
#  expirationTime: ${MINIO_EXPIRATION_TIME}

